export const DATABASE_URL = process.env.NEXT_PUBLIC_DATABASE_URL;
export const BETTER_AUTH_SECRET = process.env.NEXT_PUBLIC_BETTER_AUTH_SECRET;
export const BETTER_AUTH_BASE_URL = process.env.NEXT_PUBLIC_BETTER_AUTH_BASE_URL;